# Dimensions
TILE_SIZE = 16  # tiles are square so height==width
SCREEN_WIDTH = 52*TILE_SIZE
SCREEN_HEIGHT = 39*TILE_SIZE
TITLE_SIZE = 3*TILE_SIZE
BUTTON_WIDTH = 24*TILE_SIZE
BUTTON_HEIGHT = 4*TILE_SIZE
# Colors
BUTTON_COLOR = (224, 61, 20)
BLACK = (0, 0, 0)
BLUE = (3, 23, 165)

# GAME DYNAMICS
NUM_BUILDINGS = 25
SCALE = 3
CHARACTER_SPEED = 1

