# Dimensions
TILE_SIZE = 16  # tiles are square so height==width
SCREEN_WIDTH = 52*TILE_SIZE
SCREEN_HEIGHT = 39*TILE_SIZE
TITLE_SIZE = 86
BUTTON_SIZE = 10*TILE_SIZE
# Colors

# GAME DYNAMICS
NUM_BUILDINGS = 25
SCALE = 3
CHARACTER_SPEED = 1

