# Dimensions
TILE_SIZE = 16  # tiles are square so height==width
SCREEN_WIDTH = 52*TILE_SIZE
SCREEN_HEIGHT = 39*TILE_SIZE
TITLE_SIZE = 128
CITY_TOP = SCREEN_HEIGHT - 34*TILE_SIZE
CITY_BOTTOM = SCREEN_HEIGHT - 5*TILE_SIZE
CITY_LEFT = SCREEN_WIDTH - 47*TILE_SIZE
CITY_RIGHT = SCREEN_WIDTH - 5*TILE_SIZE

# Colors

# GAME DYNAMICS
NUM_BUILDINGS = 50
