# Dimensions
TILE_SIZE = 16  # tiles are square so height==width
SCREEN_WIDTH = 52*TILE_SIZE
SCREEN_HEIGHT = 39*TILE_SIZE
TITLE_SIZE = 128
CITY_TOP = int(0.05 * SCREEN_HEIGHT)
CITY_BOTTOM = int(0.85 * SCREEN_HEIGHT)
CITY_LEFT = int(0.05 * SCREEN_WIDTH)
CITY_RIGHT = int(0.9 * SCREEN_WIDTH)
# Colors

# GAME DYNAMICS
NUM_BUILDINGS = 25
SCALE = 3
